### PR TITLE
Implement tryCatch

### PR DESCRIPTION
**Pull request by lauratregadas**
Necessary so the function doesn't break when data available is incomplete for a certain year. For instance, 
```r
datazoom.social::load_pnadc(years=2023:2024, quarters = 4)
``` 
The function stops after failing to download 2024.4. Panelling for 2023 is not completed. 

This is indeed a problem as such code returns:
```r
Saving 2023 Q4 to
C:/Users/laura/Documents/pnadc_2023_4.rds

Downloading PNADC 2024 Q4

Data unavailable for selected quarter and year.

Error in purrr::map2():
ℹ In index: 2.
Caused by error in UseMethod():
! no applicable method for 'mutate' applied to an object of class "NULL"
Run rlang::last_trace() to see where the error occurred.
```

### CODE REVIEW

**Comment by lauratregadas** [comment]
@mariana-nmartins please run this version on your computer (run the function's script) and try to download some quarters. Tell me what error you get please.

**Comment by lauratregadas** [comment]
Not yet working.

**Comment by lauratregadas** [comment]
I have put the tryCatch as far out as possible as well as implemented several (maybe too many?) "NULL" checks/returns for when download. Anyway, whenever I run
```r
datazoom.social::load_pnadc(years=2024:2023, quarters = 4)
``` 
I still get the error of trying to apply mutate on NULL object.

Phind suggestes separating downloading from data treating.

**Comment by lauratregadas** [comment]
The version on commit 72b5ae6 does not work

**Comment by lauratregadas** [comment]
Breakthrough:

tryCatch was not working whatever I tried because **get_pnadc does not return an error** when I attempt to download a non-existing file.
Instead, it returns a message (Data unavailable for selected quarter and year.) and the NULL object.

An if statement that checks whether df is NULL after attempting to download is enough to fix our problem.

The code
```r
load_pnadc(years=2024:2023, quarters = 4)
```  
now runs smoothly.

**Review by IgorRigolon — CHANGES_REQUESTED** [review]
Atualizar [número da versão](https://r-pkgs.org/lifecycle.html#sec-lifecycle-version-number-tidyverse); criar news.md `usethis::use_news_md()` e explicar mudanças

**Pull request merged**
